### ISSUE TITLE
少了 IJKMediaFramework

### ISSUE THREAD

**Issue by xprocwin7** [LinXunFeng/LXFWeChat#2]
自己添加IJKMediaFramework，还是报错

**Comment by xunan623** [comment]
我也是这样  最后把IJKMediaFramework删除了  有使用的地方不多 直接注释  至少先能run起来

**Comment by xprocwin7** [comment]
好吧，谢谢了

**Comment by xunan623** [comment]
重点是 服务器都封装成sdk了 请问我怎么用...

**Comment by xunan623** [comment]
算了 自己注册云信key...楼主比较忙

**Comment by LinXunFeng** [comment]
这个实在不好意思，之前有需要，所以没放出测试账号，请见谅吧。现在已经放出来了，还有就是IJKMediaFramework已经上传了，这些看下README.ME就知道了

**Comment by xprocwin7** [comment]
提示，不存在该用户 那两个测试账号都用不了呀

**Comment by xunan623** [comment]
哈哈  我自己新建了一个key  只是我要自己写一个添加好友接口
