### ISSUE TITLE
no such module 'IJKMediaFramework'

### ISSUE THREAD

**Issue by narakai** [LinXunFeng/LXFWeChat#5]
我把pod仓库改回github的了，不会是这个原因吧？

**Comment by LinXunFeng** [comment]
不是，是那个IJKMediaFramework太大了，gitHub传不上来，这里有我编译好的，直接拉进项目就可以搞事了
链接:https://pan.baidu.com/s/1eRYlJ7W 密码:9iaw

**Comment by narakai** [comment]
可以了，另外还需要修改下build setting，谢谢
