### ISSUE TITLE
pod的时候 报错

### ISSUE THREAD

**Issue by afei1217** [LinXunFeng/LXFWeChat#6]
Unable to add a source with url `git@git.oschina.net:LinXunFeng/Specs.git` named `oschina-specs`.
这个git的地址有问题

**Comment by LinXunFeng** [comment]
之前是自己搞了一个远程仓库来[解决Cocoapods贼慢问题](https://juejin.im/post/5a32900a6fb9a045132aba3c)，但是码云提示xx（忘了）后我就给删了，所以这个仓库就用不了了。
现在你可以把这行取消注释
source 'https://github.com/CocoaPods/Specs.git' 
把下面这行注释或者删除掉就可以了
source 'git@git.oschina.net:LinXunFeng/Specs.git'

**Comment by afei1217** [comment]
嗯嗯 好的 谢了  您有没有添加直播前的代码吗？ 想学习一下

**Comment by LinXunFeng** [comment]
额，没有 _(:з」∠)_
